2019-04-08 22:35:02,998 - root - ERROR - put请求出错，出错原因:HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /todos/todo2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000239D28BFBA8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
2019-04-08 22:35:02,998 - root - INFO - 请求传入数据：url:http://127.0.0.1:5000/todos/todo2,key:17.0,参数:{"task":"update success"},请求方式：PUT
2019-04-08 22:35:02,999 - root - INFO - 测试用例执行完毕
